"""Added new User row 'email_verifed'

Revision ID: 001d51b5e5e2
Revises: 7948b8fbc7c3
Create Date: 2022-05-28 18:26:10.810145

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '001d51b5e5e2'
down_revision = '7948b8fbc7c3'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('user', sa.Column('email_verified', sa.Boolean(), server_default='false', nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('user', 'email_verified')
    # ### end Alembic commands ###
