"""note folder table

Revision ID: 3840a4ebb7fb
Revises: 9c75084450b4
Create Date: 2022-06-09 19:23:22.614283

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3840a4ebb7fb'
down_revision = '9c75084450b4'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('notefolder',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('label', sa.String(), nullable=False),
    sa.Column('parent_id', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['parent_id'], ['notefolder.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('note', sa.Column('note_folder', sa.Integer(), nullable=False))
    op.create_foreign_key(None, 'note', 'notefolder', ['note_folder'], ['id'])
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'note', type_='foreignkey')
    op.drop_column('note', 'note_folder')
    op.drop_table('notefolder')
    # ### end Alembic commands ###
