"""theme

Revision ID: 496928252739
Revises: 5e72afa9772f
Create Date: 2022-07-11 08:56:46.063879

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '496928252739'
down_revision = '5e72afa9772f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('theme',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=32), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('primary', sa.String(length=7), nullable=False),
    sa.Column('secondary', sa.String(length=7), nullable=False),
    sa.Column('accent', sa.String(length=7), nullable=False),
    sa.Column('neutral', sa.String(length=7), nullable=False),
    sa.Column('base', sa.String(length=7), nullable=False),
    sa.Column('info', sa.String(length=7), nullable=False),
    sa.Column('success', sa.String(length=7), nullable=False),
    sa.Column('warning', sa.String(length=7), nullable=False),
    sa.Column('error', sa.String(length=7), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('theme')
    # ### end Alembic commands ###
