"""user settings table added

Revision ID: 9c75084450b4
Revises: e6987db882ff
Create Date: 2022-06-08 10:29:10.867506

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9c75084450b4'
down_revision = 'e6987db882ff'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('usersettings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_diff', sa.Integer(), nullable=True),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('usersettings')
    # ### end Alembic commands ###
