"""init

Revision ID: b0f43221c053
Revises: 
Create Date: 2022-06-05 17:37:29.358596

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'b0f43221c053'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('note', 'type')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('type', sa.VARCHAR(length=255), server_default=sa.text("'default'::character varying"), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
