"""changed attribute

Revision ID: b606cd18b13a
Revises: 496928252739
Create Date: 2022-07-12 08:07:38.822689

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'b606cd18b13a'
down_revision = '496928252739'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('note', 'note_folder_id')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('note', sa.Column('note_folder_id', mysql.INTEGER(), autoincrement=False, nullable=True))
    op.drop_column('note', 'parent_id')
    # ### end Alembic commands ###
