"""notebook parent_id column

Revision ID: e45ef6294e93
Revises: f1e6b73f3140
Create Date: 2022-06-29 09:13:20.309330

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'e45ef6294e93'
down_revision = 'f1e6b73f3140'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_column('notebook', 'about')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('notebook', sa.Column('about', mysql.VARCHAR(length=256), nullable=True))
    op.drop_column('notebook', 'parent_id')
    # ### end Alembic commands ###
